### ISSUE TITLE
UI impovement

### ISSUE THREAD

**Issue by xni7** [SafetyGraphics/volcanoPlot#15]
One comment: current app has two separate buttons on top to be efficient and fast processing – one is for “Obtain statistics”, and the other one is for “Update plot”. It works like this:   if subgroup or label changes and no need to re-calculate statistics, the users only need to click “Update Plot”.  However, if test statistics change and/or SOC/PT/Other level changes, the users need to click “Obtain statistics” button.  If team feel this might cause confusion, please feel free to make change.

**Comment by isaaczhao-alk** [comment]
Will have to put data used to generate the plot within an observe({ isolate ({ ..... }) })  so that the data to graph (and hence the graph itself) will automatically only update under these conditions

**Comment by isaaczhao-alk** [comment]
changing statistical measurement, p value option, and axis reference lines no longer require obtain statistics
