### ISSUE TITLE
refactor getStatistics.R

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/volcanoPlot#34]
Can be simplified. Data manipulation (cleaning, filtering, etc) should be moved it a separate function or done directly in the shiny app. This function should just take a cleaned data as input and return a data set with test results (estimates, p-values, confidence intervals, etc). Ideally, this should also be set up so that it can  be run multiple times to produce output for paneled displays.

**Comment by jwildfire** [comment]
Inputs 
-  `data` - list of data.frames with both AE and Demographic domains included (e.g. `list(AEs=ae_data, Labs=lab_data)`) Data sets will be merged as part of this process
- `data.mapping` - list of data mappings used in the function (e.g. id_column, etc)
  - `stratification_col` - the column used to calculate points on the volcano plot (typically 'soc' or 'pt')
  - `group_col` - the column containing the comparison group data (typically treatment)
  - `reference_group` and `comparison_group` - the control and comparison groups for the current calculation
  - `id_col` (this should be present in both AE and Demog)
 - `calculation.type` - valid options are 'rate.difference', 'rate.ratio', 'risk.ratio', 'risk.difference', 'hazard.ratio'

Outputs - return a dataset with one row per calculation (e.g. system organ class) with the following columns:
- `strata` - the SOC for the current calcalation
- various group statistics (rate, numerator, denominator count, etc)
- `est.type`
- `est.values`
- `p`
- `p.adj`

**Comment by isaaczhao-alk** [comment]
Refactored works with PT. SOC may not work.

**Comment by isaaczhao-alk** [comment]
Refactored works with PT. SOC may not work.
