### ISSUE TITLE
Render plot with existing library

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/volcanoPlot#35]
Consider rendering plot with existing library like [this](https://github.com/kevinblighe/EnhancedVolcano) one. 

cc: @xni7

**Comment by jwildfire** [comment]
@nandriychuk @anhtr I think this is worth looking in to more. If there is a good existing package for the visualization, we should strongly consider using it instead of making our own.

**Comment by anhtr** [comment]
> @nandriychuk @anhtr I think this is worth looking in to more. If there is a good existing package for the visualization, we should strongly consider using it instead of making our own.

@jwildfire @nandriychuk I agree. I do have a question about dependencies: For our specific use case, do we care about minimizing dependencies? The EnhancedVolcano library, for example, imports the `airway` and `pasilla` dataset and `org.Hs.eg.db`, which I think is not necessary here.

**Comment by jwildfire** [comment]
@anhtr implemented {enhancedVolcano} in `volcanoPlotEnh`, but I think a hand-rolled plotly graph is probably going to be easier to customize, so we'll stick with that for the time being.
