### ISSUE TITLE
Add toggle between subject and event level data

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/volcanoPlot#4]
Similar to the existing functionality in the ae-explorer - [example](https://rhoinc.github.io/aeexplorer/test-page/), [repo](https://github.com/RhoInc/aeexplorer)

![image](https://user-images.githubusercontent.com/3680095/69349900-5bcbea80-0c57-11ea-8f53-98bed55cda4a.png)

Request from 2019-11-20 group call.

**Comment by isaaczhao-alk** [comment]
What should be run when Event level data is selected? No measures of association can be used when "Event" is selected.

![image](https://user-images.githubusercontent.com/62663896/84849111-9dbce380-b022-11ea-85cb-6c5637a16e1c.png)

**Comment by isaaczhao-alk** [comment]
disabled summary by events for now
