### ISSUE TITLE
Run volcano plot code on updated getStats output

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/volcanoPlot#44]

**Comment by anhtr** [comment]
https://github.com/SafetyGraphics/volcanoPlot/blob/888699a70d23282c69801158ebb464fdff7244a8/R/volcanoPlot.R#L24-L40

This worked great on the updated getStats output, but as we discussed an existing volcano plot function maybe lower maintenance. I am testing out EnhancedVolcano.

**Comment by anhtr** [comment]
https://github.com/SafetyGraphics/volcanoPlot/blob/1fe58bdaeb0f4a79dbb56d039d9f1ae803e76d10/R/volcanoPlot.R#L43-L57

![plot_zoom](https://user-images.githubusercontent.com/22552876/159040224-ed1c6dca-8133-40fd-abdc-5919e0a4ebe9.png)

A rough plot made with EnhancedVolcano. With tweaks it could look better, but a caveat is that it won't support plotly.
