### ISSUE TITLE
Show AE listing when a point is clicked

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/volcanoPlot#58]

**Comment by anhtr** [comment]
I'm not sure exactly what this means. May you give an example or description, @jwildfire? I'm actually working on a few (unpushed) updates to the volcanoPlot function, so I think I will take on this as well.

**Comment by jwildfire** [comment]
Idea make a linked listing from the AE data set showing all of the AEs in the selected strata (usually system organ class) for the clicked point.

**Comment by anhtr** [comment]
I just want to add a reference on how this may be achieved. I'm not sure if this could be done just inside the `volcanoPlot` function, or `getStats` and the server logic also need to be changed.
