### ISSUE TITLE
Allow user to select SOC or PT as unit of analysis in Shiny UI

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/volcanoPlot#65]

**Comment by nandriychuk** [comment]
Do we want to use AETERM (Reported Term for the Adverse Event) or AEPTCD (Preferred term) column for PT? 
And for SOC:  AEBODSYS (Body System or Organ Class) or AESOC (Primary System Organ Class)?

**Comment by nandriychuk** [comment]
Could you also please describe the expected app behavior in more detail?

**Comment by jwildfire** [comment]
@nandriychuk I think we'd just want a dropdown that lets the user select SOC/PT and updates the chart accordingly. Exact column should be specified by the user. Would likely just need to add a new setting [here](https://github.com/SafetyGraphics/volcanoPlot/blob/1b328c3b5f7edc85f5114cd1b167ad92f7afab3f/R/volcanoApp.R#L13-L16). We use `term_col` for preferred term over in safetyGraphics/safetyCharts, so we should probably just re-use that here as well.
