### ISSUE TITLE
Generalize app to accept other types of source data such as ADaM

### ISSUE THREAD

**Issue by xni7** [SafetyGraphics/volcanoPlot#7]
For current version, SDTM like data set are used as input, which is a simple merge of DM and AE
ADaM and other non-standard data format could also be used if mapping variables names to the list of variables used. 

Consider adding mapping.

**Comment by xni7** [comment]
Current SDTM data structure

Variable   name | Note
-- | --
USUBJID |  
AE   related information : mainly from SDTM. AE.    Additonal infromation, such as HLGT, HLT, or user customized seach   category, can be added.
AESEQ |  
AESTDT | AE onset date
AESTDY | AE onset relative study day
AEENDT | AE end date
AEENDY | AE end relative study day
AETERM | AE reported tem
AEDECOD | AE PT
AEBODSYS | Primary SOC
AESER | Serious AE or not
AEONGO | whether AE is ongoing
AESEV | AE severity: such as moderate, mild etc.    Oncology might consider ATOXGR
AEREL | Causality:  a little modication is   done: convert "likely", "possible likly", " not   likely" to a simple "Yes" or "No"
AEOUT | Outcome
STUDYFL | flag to indicate whether AE onset during study period.
TRTEMFL | Treatment emergent flag
Demograhy   related mainly from STDM. DM
SITE |  
SITEID |  
AGE |  
SEX |  
RACE |  
ARM |  
ARMCD |  
SBJTSTAT | subjet status
RFSTDTC | Treatment start date
RFENDTC | treatment end date
RFENDY | treatment end relative study day
SAFFL | safety population flag

**Comment by isaaczhao-alk** [comment]
Currently has an Import ADAM option but only SDTM upload seems to work. Data options are not reactive to ADAM. Suggest toggle to select either SDTM or ADAM instead of two separate upload buttons.

**Comment by jwildfire** [comment]
Refactor in #45 sets this up.
